### ISSUE TITLE
Update app store descriptions

### ISSUE THREAD

**Issue by jaredpreston** [ory/kratos-selfservice-ui-react-native#10]
**Describe the bug**

The app store descriptions are not reflective of what the demo / app is about.

**Expected behavior**

The appstore description should tell a developer that they can install the Ory mobile example app to connect to a hosted instance of Kratos. It showcases how the app calls and sends commands to the Kratos API to register a user and receives back a payload from the Kratos API. The example application can be forked on GitHub and used and customized by a developer to showcase registration for their own mobile applications. It shows how easily registration is automated and software can be replicated.

**Comment by aeneasr** [comment]
Do you have a concrete suggestion for the description that I could copy&paste to the store? :)

**Comment by jaredpreston** [comment]
This is the Ory example app for developers to see how easy it is to set up user registration. The app connects to a hosted instance of Ory Kratos via the API. You can use the app to register a user and create a profile. The app sends data to the Kratos API and receives back a payload which you can inspect to see how everything works, and how the profile is set up.

You can fork the code for the app on GitHub, customize it, and try it for yourself with your own mobile applications. You will see how easily registration and profile creation can be automated and software can be replicated. No more heavy lifting and instant gratification out of the box :)
