### ISSUE TITLE
Fix login button behavior on Android

### ISSUE THREAD

**Issue by jaredpreston** [ory/kratos-selfservice-ui-react-native#11]
**Describe the bug**

The login button cannot be clicked while the cursor is still focused in the E-Mail or Password entry fields. You have to tap the screen to drop the keyboard down again and only then can you click on the Sign in button.

**To Reproduce**

Enter either email address or password in the field and try clicking on the Sign in button.

**Expected behavior**

I should be able to click on the sign in button without having to tap on the screen to get the focus back on the page.

**Environment**

Android phone OnePlus 6T
Model A6013
Android version 10, Kernel version 4.9.179-perf+
OxygenOS version 10.3.6

**Comment by aeneasr** [comment]
This is caused by a SafeAreaView component. Basically it overlays all other elements which allows us to catch if someone clicks the link. There might be a better solution for this though!

**Comment by jaredpreston** [comment]
What do you mean by "catch someone"? Are we kicking off an analytics beacon of some sort?

**Comment by aeneasr** [comment]
Ah no, this means that we catch the "event" when someone taps outside of the keyboard area, which triggers the keyboard to hide!
