### ISSUE TITLE
Can't proceed to login form.

### ISSUE THREAD

**Issue by rodelrebucas** [ory/kratos-selfservice-ui-react-native#36]
**Describe the bug**

Downloaded the app on Android 10 when I opened it, it's stuck on loading screen icon. 

**To Reproduce**

1. Download the app.

2. Open it.

**Expected behavior**

Once opened, I should be presented with login form.

**Environment**

- Android 10

**Additional context**

- ORY Profile App version 0.5.11

**Comment by aeneasr** [comment]
This could potentially happen when something with the update mechanism fails. We don't have android test devices unfortunately available at the moment. :(

What version of the app do you have?

**Comment by rodelrebucas** [comment]
Hi, app version is 0.5.11.

**Comment by aeneasr** [comment]
I was able to see this on iOS as well - will take a look next week (or if you want, contribs welcomed :) )

**Comment by aeneasr** [comment]
So I believe this should be fixed now - at least on iOS it is working again. Could you recheck please? :)

**Comment by aeneasr** [comment]
Ah sorry, the app is still in review - should be available in a day or so

**Comment by rodelrebucas** [comment]
Sure, I will check.

**Comment by rodelrebucas** [comment]
I have tested the updated app and now I can proceed to login and signup. Closing issue now.

**Comment by aeneasr** [comment]
Nice!
