### ISSUE TITLE
App crashes on ios17

### ISSUE THREAD

**Issue by jetaggart** [ory/kratos-selfservice-ui-react-native#83]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos-selfservice-ui-react-native/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos-selfservice-ui-react-native/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When I download and launch via `npm run ios` I get hit with the below error. I figured out how to fix this was to go into the contrib sdk package and run `npm prepare` which was not obvious and not documented.

```
Metro has encountered an error: While trying to resolve module `@ory/client` from file `/Users/jetaggart/code/scratch/kratos-selfservice-ui-react-native/src/components/Routes/Settings.tsx`, the package `/Users/jetaggart/code/scratch/kratos-selfservice-ui-react-native/contrib/sdk/generated/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/jetaggart/code/scratch/kratos-selfservice-ui-react-native/contrib/sdk/generated/dist/index.js`. Indeed, none of these files exist:

  * /Users/jetaggart/code/scratch/kratos-selfservice-ui-react-native/contrib/sdk/generated/dist/index.js(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs)
  * /Users/jetaggart/code/scratch/kratos-selfservice-ui-react-native/contrib/sdk/generated/dist/index.js/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs): /Users/jetaggart/code/scratch/kratos-selfservice-ui-react-native/node_modules/metro/src/node-haste/DependencyGraph.js (289:17)

  287 |         }
  288 |         if (error instanceof InvalidPackageError) {
> 289 |           throw new PackageResolutionError({
      |                 ^
  290 |             packageError: error,
  291 |             originModulePath: from,
  292 |             targetModuleName: to,

ABI49_0_0RCTFatal
__37-[ABI49_0_0RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_drain
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0
0x0
```

### Reproducing the bug

see above

### Version

master

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by yasha-spare** [comment]
Same error for me, trying to run on an iOS 14 Simulator device.  Check out master in this repo, npm install (works fine), start the app, crashes with this `Unable to resolve "@ory/client"` error.

**Comment by jetaggart** [comment]
This seems fixed
